version: '3.1'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: agronorte123
      POSTGRES_USER: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: agronorte123
    volumes:
      - odoo-web-data:/var/lib/odoo

  n8n:
    image: n8nio/n8n:1.0.0
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
    volumes:
      - n8n-data:/home/node/.n8n
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-web-data:
  n8n-data: